version: 1.0.0
ignore:
  - id: endorignore-1
    username: spanigrahi@endor.ai@google@api-key
    update_time: 2026-09-02 09:15:33 UTC
    vuln_id: GHSA-mqqf-5wvp-8fh8
    reason: risk-accepted
    comments: testing shrabani 1212
